from __future__ import annotations
import json
from pathlib import Path
from config import DUCKDB_TEMP, HIRID_MAP_GLOB, HIRID_ROOT, RESULTS_DIR, SICDB_ROOT
import duckdb
ROOT = HIRID_ROOT
OUT = RESULTS_DIR
OUT.mkdir(parents=True, exist_ok=True)
PHARMA_GLOB = str(ROOT / 'raw_stage' / 'pharma_records' / 'csv' / 'part-*.csv').replace('\\', '/')
TARGET_IDS = (1000605, 1000489, 1000490)
METAMIZOLE_IDS = (1000605,)
PARACETAMOL_IDS = (1000489, 1000490)
PRESSOR_IDS = (1000462, 1000656, 1000657, 1000658, 71, 1000750, 1000649, 1000650, 1000655, 112, 113)
CSV_COLUMNS = "{patientid: 'INTEGER', pharmaid: 'INTEGER', givenat: 'TIMESTAMP', enteredentryat: 'TIMESTAMP', givendose: 'DOUBLE', cumulativedose: 'DOUBLE', fluidamount_calc: 'DOUBLE', cumulfluidamount_calc: 'DOUBLE', doseunit: 'VARCHAR', route: 'VARCHAR', infusionid: 'VARCHAR', typeid: 'INTEGER', subtypeid: 'DOUBLE', recordstatus: 'INTEGER'}"
MAP_GLOB = HIRID_MAP_GLOB
con = duckdb.connect()
con.execute("SET memory_limit='768MB'")
con.execute('SET threads=2')
con.execute('SET preserve_insertion_order=false')
con.execute(f"SET temp_directory='{DUCKDB_TEMP.as_posix()}'")
con.execute(f"\n    CREATE TEMP TABLE target AS\n    SELECT\n        patientid::INTEGER AS patientid,\n        pharmaid::INTEGER AS pharmaid,\n        givenat::TIMESTAMP AS givenat,\n        route,\n        givendose::DOUBLE AS givendose,\n        infusionid::BIGINT AS infusionid,\n        typeid::INTEGER AS typeid,\n        subtypeid::DOUBLE AS subtypeid,\n        recordstatus::INTEGER AS recordstatus\n    FROM read_csv('{PHARMA_GLOB}', union_by_name=true, header=true, columns={CSV_COLUMNS}, ignore_errors=true)\n    WHERE pharmaid IN {TARGET_IDS}\n      AND givenat IS NOT NULL\n    ")

def rows(sql: str):
    return [dict(zip([d[0] for d in con.description], row)) for row in con.execute(sql).fetchall()]

def scalar(sql: str):
    return con.execute(sql).fetchone()[0]
all_by_product = rows('\n    SELECT pharmaid, route, typeid, subtypeid,\n           COUNT(*) AS rows, COUNT(DISTINCT patientid) AS patients,\n           COUNT(*) FILTER (WHERE givendose > 0) AS positive_rows,\n           COUNT(*) FILTER (WHERE (recordstatus & 2) = 0 AND (recordstatus & 32) = 0) AS status_valid_rows\n    FROM target\n    GROUP BY ALL\n    ORDER BY pharmaid, route, typeid, subtypeid\n    ')
con.execute("\n    CREATE TEMP TABLE eligible AS\n    SELECT *\n    FROM target\n    WHERE route IN ('iv-inj', 'iv-inf', 'cv-inj', 'cv-inf')\n      AND givendose > 0\n      AND (recordstatus & 2) = 0\n      AND (recordstatus & 32) = 0\n    ")
eligible_by_product = rows('\n    SELECT pharmaid, COUNT(*) AS administrations, COUNT(DISTINCT patientid) AS patients,\n           COUNT(DISTINCT infusionid) AS infusion_ids\n    FROM eligible\n    GROUP BY pharmaid\n    ORDER BY pharmaid\n    ')
met_patients = scalar(f'SELECT COUNT(DISTINCT patientid) FROM eligible WHERE pharmaid IN {METAMIZOLE_IDS}')
para_patients = scalar(f'SELECT COUNT(DISTINCT patientid) FROM eligible WHERE pharmaid IN {PARACETAMOL_IDS}')
both_patients = scalar(f'\n    SELECT COUNT(*) FROM (\n      SELECT patientid\n      FROM eligible\n      GROUP BY patientid\n      HAVING BOOL_OR(pharmaid IN {METAMIZOLE_IDS})\n         AND BOOL_OR(pharmaid IN {PARACETAMOL_IDS})\n    )\n    ')
con.execute(f"\n    CREATE TEMP TABLE eligible_pressor AS\n    SELECT DISTINCT e.rowid AS target_rowid\n    FROM eligible e\n    JOIN read_csv('{PHARMA_GLOB}', union_by_name=true, header=true, columns={CSV_COLUMNS}, ignore_errors=true) p\n      ON p.patientid::INTEGER = e.patientid\n     AND p.pharmaid::INTEGER IN {PRESSOR_IDS}\n     AND p.route IN ('cv-inf', 'iv-inf')\n     AND p.givendose::DOUBLE > 0\n     AND p.givenat::TIMESTAMP BETWEEN e.givenat - INTERVAL 10 MINUTE\n                                  AND e.givenat + INTERVAL 10 MINUTE\n     AND (p.recordstatus::INTEGER & 2) = 0\n     AND (p.recordstatus::INTEGER & 32) = 0\n    ")
pressor_total = scalar('SELECT COUNT(*) FROM eligible')
pressor_hits = scalar('SELECT COUNT(*) FROM eligible_pressor')
pressor_by_product = rows('\n    SELECT e.pharmaid, COUNT(DISTINCT e.rowid) AS administrations_with_pressor_proxy\n    FROM eligible e JOIN eligible_pressor p ON p.target_rowid = e.rowid\n    GROUP BY e.pharmaid ORDER BY e.pharmaid\n    ')
result = {'dataset': 'HiRID 1.1.1', 'reference': {'metamizole_iv': {'pharmaids': list(METAMIZOLE_IDS), 'name': 'Novalgin inj lös 50% 2 ml'}, 'paracetamol_iv': {'pharmaids': list(PARACETAMOL_IDS), 'name': 'Perfalgan 1g/500 mg'}}, 'definitions': {'eligible': 'route in {iv-inj, iv-inf, cv-inj, cv-inf}, givendose>0, recordstatus bits 2 and 32 absent', 'pressor_proxy': 'valid cv-inf/iv-inf pressor record within +/-10 minutes of analgesic givenat', 'pressor_ids': list(PRESSOR_IDS)}, 'all_target_rows_by_product_route': all_by_product, 'eligible_by_product': eligible_by_product, 'eligible_patients': {'metamizole_only_or_any': int(met_patients), 'paracetamol_only_or_any': int(para_patients), 'both_drugs': int(both_patients)}, 'pressor_proxy': {'eligible_administrations': int(pressor_total), 'with_pressor_proxy': int(pressor_hits), 'fraction': pressor_hits / pressor_total if pressor_total else None, 'by_product': pressor_by_product}, 'kill_lines': {'both_drugs_patients_ge_1000': bool(both_patients >= 1000), 'proceed_to_map_audit': bool(both_patients >= 1000)}}
if both_patients >= 1000:
    con.execute('\n        CREATE TEMP TABLE both_patient AS\n        SELECT patientid\n        FROM eligible\n        GROUP BY patientid\n        HAVING BOOL_OR(pharmaid IN (1000605))\n           AND BOOL_OR(pharmaid IN (1000489, 1000490))\n        ')
    con.execute(f"\n        CREATE TEMP TABLE map_event_summary AS\n        SELECT\n            e.rowid AS target_rowid,\n            e.patientid,\n            e.pharmaid,\n            e.givenat,\n            AVG(m.vm5) FILTER (WHERE m.datetime >= e.givenat - INTERVAL 30 MINUTE AND m.datetime < e.givenat) AS pre_mean,\n            REGR_SLOPE(m.vm5, EPOCH(m.datetime - e.givenat)) FILTER (WHERE m.datetime >= e.givenat - INTERVAL 30 MINUTE AND m.datetime < e.givenat) AS pre_slope_per_min,\n            AVG(m.vm13) FILTER (WHERE m.datetime >= e.givenat - INTERVAL 30 MINUTE AND m.datetime < e.givenat) AS pre_temp,\n            AVG(m.vm5) FILTER (WHERE m.datetime >= e.givenat AND m.datetime <= e.givenat + INTERVAL 120 MINUTE) AS post_mean,\n            MIN(m.vm5) FILTER (WHERE m.datetime >= e.givenat AND m.datetime <= e.givenat + INTERVAL 120 MINUTE) AS post_min,\n            COUNT(*) FILTER (WHERE m.datetime >= e.givenat - INTERVAL 30 MINUTE AND m.datetime < e.givenat) AS pre_n,\n            COUNT(*) FILTER (WHERE m.datetime >= e.givenat AND m.datetime <= e.givenat + INTERVAL 120 MINUTE) AS post_n\n        FROM eligible e\n        JOIN both_patient bp ON bp.patientid = e.patientid\n        JOIN read_parquet('{MAP_GLOB}') m\n          ON m.patientid = e.patientid\n         AND m.datetime BETWEEN e.givenat - INTERVAL 30 MINUTE AND e.givenat + INTERVAL 120 MINUTE\n         AND m.vm5 IS NOT NULL\n        GROUP BY e.rowid, e.patientid, e.pharmaid, e.givenat\n        ")
    map_by_product = rows('\n        SELECT pharmaid,\n               COUNT(*) AS events_with_map,\n               COUNT(*) FILTER (WHERE pre_n >= 3 AND post_n >= 3) AS events_with_min_window,\n               AVG(pre_mean) FILTER (WHERE pre_n >= 3 AND post_n >= 3) AS pre_mean,\n               AVG(pre_slope_per_min * 60) FILTER (WHERE pre_n >= 3 AND post_n >= 3) AS mean_pre_slope_per_hour,\n               AVG(post_min - pre_mean) FILTER (WHERE pre_n >= 3 AND post_n >= 3) AS mean_post_min_change,\n               MEDIAN(post_min - pre_mean) FILTER (WHERE pre_n >= 3 AND post_n >= 3) AS median_post_min_change,\n               AVG(post_mean - pre_mean) FILTER (WHERE pre_n >= 3 AND post_n >= 3) AS mean_post_mean_change,\n               COUNT(*) FILTER (WHERE pre_n >= 3 AND post_n >= 3 AND post_min < 65) AS post_map_below_65\n        FROM map_event_summary\n        GROUP BY pharmaid ORDER BY pharmaid\n        ')
    paired = rows('\n        WITH patient_drug AS (\n          SELECT patientid,\n                 AVG(post_min - pre_mean) FILTER (WHERE pharmaid = 1000605 AND pre_n >= 3 AND post_n >= 3) AS met_change,\n                 AVG(post_min - pre_mean) FILTER (WHERE pharmaid IN (1000489, 1000490) AND pre_n >= 3 AND post_n >= 3) AS para_change,\n                 AVG(pre_mean) FILTER (WHERE pharmaid = 1000605 AND pre_n >= 3 AND post_n >= 3) AS met_pre_mean,\n                 AVG(pre_mean) FILTER (WHERE pharmaid IN (1000489, 1000490) AND pre_n >= 3 AND post_n >= 3) AS para_pre_mean,\n                 AVG(pre_slope_per_min * 60) FILTER (WHERE pharmaid = 1000605 AND pre_n >= 3 AND post_n >= 3) AS met_pre_slope_per_hour,\n                 AVG(pre_slope_per_min * 60) FILTER (WHERE pharmaid IN (1000489, 1000490) AND pre_n >= 3 AND post_n >= 3) AS para_pre_slope_per_hour,\n                 COUNT(*) FILTER (WHERE pharmaid = 1000605 AND pre_n >= 3 AND post_n >= 3) AS met_events,\n                 COUNT(*) FILTER (WHERE pharmaid IN (1000489, 1000490) AND pre_n >= 3 AND post_n >= 3) AS para_events\n          FROM map_event_summary\n          GROUP BY patientid\n        )\n        SELECT COUNT(*) FILTER (WHERE met_change IS NOT NULL AND para_change IS NOT NULL) AS paired_patients,\n               AVG(met_change - para_change) FILTER (WHERE met_change IS NOT NULL AND para_change IS NOT NULL) AS mean_within_patient_difference,\n               MEDIAN(met_change - para_change) FILTER (WHERE met_change IS NOT NULL AND para_change IS NOT NULL) AS median_within_patient_difference,\n               AVG(met_pre_mean - para_pre_mean) FILTER (WHERE met_pre_mean IS NOT NULL AND para_pre_mean IS NOT NULL) AS mean_within_patient_pre_level_difference,\n               MEDIAN(met_pre_mean - para_pre_mean) FILTER (WHERE met_pre_mean IS NOT NULL AND para_pre_mean IS NOT NULL) AS median_within_patient_pre_level_difference,\n               AVG(met_pre_slope_per_hour - para_pre_slope_per_hour) FILTER (WHERE met_pre_slope_per_hour IS NOT NULL AND para_pre_slope_per_hour IS NOT NULL) AS mean_within_patient_pre_slope_difference_per_hour,\n               MEDIAN(met_pre_slope_per_hour - para_pre_slope_per_hour) FILTER (WHERE met_pre_slope_per_hour IS NOT NULL AND para_pre_slope_per_hour IS NOT NULL) AS median_within_patient_pre_slope_difference_per_hour\n        FROM patient_drug\n        ')
    result['map_audit'] = {'by_product': map_by_product, 'within_patient': paired}
    con.execute(f"\n        CREATE TEMP TABLE press_raw2 AS\n        SELECT patientid::INTEGER AS patientid, givenat::TIMESTAMP AS givenat,\n               givendose::DOUBLE AS givendose, infusionid::VARCHAR AS infusionid\n        FROM read_csv('{PHARMA_GLOB}', union_by_name=true, header=true, columns={CSV_COLUMNS}, ignore_errors=true)\n        WHERE pharmaid IN {PRESSOR_IDS}\n          AND patientid IN (SELECT patientid FROM both_patient)\n          AND givenat IS NOT NULL AND givendose > 0\n          AND route IN ('cv-inf', 'iv-inf')\n          AND (recordstatus & 2) = 0 AND (recordstatus & 32) = 0\n        ")
    con.execute('\n        CREATE TEMP TABLE press_int2 AS\n        WITH x AS (\n          SELECT *, LEAD(givenat) OVER (PARTITION BY patientid, infusionid ORDER BY givenat) AS next_at\n          FROM press_raw2\n        )\n        SELECT patientid, infusionid, givenat AS start_at,\n               CASE WHEN next_at IS NOT NULL AND next_at <= givenat + INTERVAL 15 MINUTE\n                    THEN next_at ELSE givenat + INTERVAL 10 MINUTE END AS stop_at\n        FROM x\n        ')
    con.execute('\n        CREATE TEMP TABLE real_combined AS\n        SELECT m.*,\n               CASE WHEN EXISTS (SELECT 1 FROM press_int2 p WHERE p.patientid=m.patientid AND p.start_at <= m.givenat AND m.givenat < p.stop_at) THEN 1 ELSE 0 END AS pressor_proxy\n        FROM map_event_summary m\n        WHERE pre_n >= 3 AND post_n >= 3\n        ')
    con.execute('\n        CREATE TEMP TABLE fake_candidates AS\n        SELECT r.target_rowid AS real_rowid, r.patientid,\n               r.givenat + off.hours * INTERVAL 1 HOUR AS fake_at,\n               r.pre_mean AS real_pre_mean,\n               r.pre_slope_per_min AS real_pre_slope,\n               r.pre_temp AS real_pre_temp,\n               r.pressor_proxy\n        FROM real_combined r\n        CROSS JOIN (VALUES (-16), (-12), (-8), (8), (12), (16)) off(hours)\n        WHERE NOT EXISTS (\n          SELECT 1 FROM eligible x\n          WHERE x.patientid = r.patientid\n            AND x.givenat BETWEEN r.givenat + off.hours * INTERVAL 1 HOUR - INTERVAL 4 HOUR\n                              AND r.givenat + off.hours * INTERVAL 1 HOUR + INTERVAL 4 HOUR\n        )\n        ')
    con.execute('\n        CREATE TEMP TABLE fake_candidates_state AS\n        SELECT f.*,\n               CASE WHEN EXISTS (SELECT 1 FROM press_int2 p WHERE p.patientid=f.patientid AND p.start_at <= f.fake_at AND f.fake_at < p.stop_at) THEN 1 ELSE 0 END AS fake_pressor_proxy\n        FROM fake_candidates f\n        ')
    con.execute(f"\n        CREATE TEMP TABLE fake_summary_raw AS\n        SELECT f.real_rowid, f.patientid, f.fake_at,\n               f.real_pre_mean, f.real_pre_slope, f.real_pre_temp, f.pressor_proxy, f.fake_pressor_proxy,\n               AVG(m.vm5) FILTER (WHERE m.datetime >= f.fake_at - INTERVAL 30 MINUTE AND m.datetime < f.fake_at) AS pre_mean,\n               REGR_SLOPE(m.vm5, EPOCH(m.datetime - f.fake_at)) FILTER (WHERE m.datetime >= f.fake_at - INTERVAL 30 MINUTE AND m.datetime < f.fake_at) AS pre_slope_per_min,\n               AVG(m.vm13) FILTER (WHERE m.datetime >= f.fake_at - INTERVAL 30 MINUTE AND m.datetime < f.fake_at) AS pre_temp,\n               MIN(m.vm5) FILTER (WHERE m.datetime >= f.fake_at AND m.datetime <= f.fake_at + INTERVAL 120 MINUTE) AS post_min,\n               AVG(m.vm5) FILTER (WHERE m.datetime >= f.fake_at AND m.datetime < f.fake_at + INTERVAL 60 MINUTE) AS mean_30_60,\n               AVG(m.vm5) FILTER (WHERE m.datetime >= f.fake_at + INTERVAL 60 MINUTE AND m.datetime < f.fake_at + INTERVAL 90 MINUTE) AS mean_60_90,\n               AVG(m.vm5) FILTER (WHERE m.datetime >= f.fake_at + INTERVAL 90 MINUTE AND m.datetime <= f.fake_at + INTERVAL 120 MINUTE) AS mean_90_120,\n               COUNT(*) FILTER (WHERE m.datetime >= f.fake_at - INTERVAL 30 MINUTE AND m.datetime < f.fake_at) AS pre_n,\n               COUNT(*) FILTER (WHERE m.datetime >= f.fake_at AND m.datetime <= f.fake_at + INTERVAL 120 MINUTE) AS post_n\n        FROM fake_candidates_state f\n        JOIN read_parquet('{MAP_GLOB}') m\n          ON m.patientid = f.patientid\n         AND m.datetime BETWEEN f.fake_at - INTERVAL 30 MINUTE AND f.fake_at + INTERVAL 120 MINUTE\n         AND m.vm5 IS NOT NULL\n        GROUP BY ALL\n        ")
    con.execute('\n        CREATE TEMP TABLE fake_matched AS\n        SELECT * EXCLUDE (distance),\n               ROW_NUMBER() OVER (PARTITION BY real_rowid ORDER BY distance) AS match_rank\n        FROM (\n          SELECT f.*,\n                 ABS(f.pre_mean - r.pre_mean) / 5.0\n                 + ABS(f.pre_slope_per_min - r.pre_slope_per_min) * 60.0 / 2.0\n                 + ABS(f.pre_temp - r.pre_temp) / 1.0\n                 + CASE WHEN f.fake_pressor_proxy <> r.pressor_proxy THEN 10.0 ELSE 0.0 END AS distance\n          FROM fake_summary_raw f\n          JOIN real_combined r ON r.target_rowid = f.real_rowid\n          WHERE f.pre_n >= 3 AND f.post_n >= 3\n        )\n        ')
    con.execute('CREATE TEMP TABLE fake_best AS SELECT * EXCLUDE (match_rank) FROM fake_matched WHERE match_rank = 1')
    con.execute(f"\n        CREATE TEMP TABLE cantais_real AS\n        WITH idx AS (\n          SELECT r.target_rowid AS rowid, r.patientid, r.givenat AS index_at\n          FROM real_combined r\n        ), sched AS (\n          SELECT * FROM idx CROSS JOIN (VALUES (5),(10),(15),(20),(25),(30),(40),(50),(60),(75),(90),(105),(120),(135),(150),(165),(180)) s(minute)\n        ), points AS (\n          SELECT s.rowid, s.patientid, s.index_at,\n                 s.minute, arg_min(m.vm5, ABS(EPOCH(m.datetime-(s.index_at+s.minute*INTERVAL 1 MINUTE)))) AS map_value\n          FROM sched s JOIN read_parquet('{MAP_GLOB}') m\n            ON m.patientid=s.patientid AND m.vm5 IS NOT NULL\n           AND m.datetime BETWEEN s.index_at+s.minute*INTERVAL 1 MINUTE-INTERVAL 3 MINUTE\n                              AND s.index_at+s.minute*INTERVAL 1 MINUTE+INTERVAL 3 MINUTE\n          GROUP BY ALL\n        ), base AS (\n          SELECT i.rowid, arg_max(m.vm5,m.datetime) AS baseline\n          FROM idx i JOIN read_parquet('{MAP_GLOB}') m\n            ON m.patientid=i.patientid AND m.vm5 IS NOT NULL AND m.datetime<i.index_at\n          GROUP BY i.rowid\n        )\n        SELECT b.rowid, b.baseline, COUNT(p.map_value) AS scheduled_points,\n               MAX(CASE WHEN p.map_value <= b.baseline*0.85 THEN 1 ELSE 0 END) AS event\n        FROM base b LEFT JOIN points p ON p.rowid=b.rowid\n        GROUP BY b.rowid,b.baseline\n        ")
    con.execute(f"\n        CREATE TEMP TABLE cantais_fake AS\n        WITH idx AS (\n          SELECT f.real_rowid AS rowid, f.patientid, f.fake_at AS index_at\n          FROM fake_best f\n        ), sched AS (\n          SELECT * FROM idx CROSS JOIN (VALUES (5),(10),(15),(20),(25),(30),(40),(50),(60),(75),(90),(105),(120),(135),(150),(165),(180)) s(minute)\n        ), points AS (\n          SELECT s.rowid, s.patientid, s.index_at,\n                 s.minute, arg_min(m.vm5, ABS(EPOCH(m.datetime-(s.index_at+s.minute*INTERVAL 1 MINUTE)))) AS map_value\n          FROM sched s JOIN read_parquet('{MAP_GLOB}') m\n            ON m.patientid=s.patientid AND m.vm5 IS NOT NULL\n           AND m.datetime BETWEEN s.index_at+s.minute*INTERVAL 1 MINUTE-INTERVAL 3 MINUTE\n                              AND s.index_at+s.minute*INTERVAL 1 MINUTE+INTERVAL 3 MINUTE\n          GROUP BY ALL\n        ), base AS (\n          SELECT i.rowid, arg_max(m.vm5,m.datetime) AS baseline\n          FROM idx i JOIN read_parquet('{MAP_GLOB}') m\n            ON m.patientid=i.patientid AND m.vm5 IS NOT NULL AND m.datetime<i.index_at\n          GROUP BY i.rowid\n        )\n        SELECT b.rowid, b.baseline, COUNT(p.map_value) AS scheduled_points,\n               MAX(CASE WHEN p.map_value <= b.baseline*0.85 THEN 1 ELSE 0 END) AS event\n        FROM base b LEFT JOIN points p ON p.rowid=b.rowid\n        GROUP BY b.rowid,b.baseline\n        ")
    result['task_posthoc_cantais_definition'] = {'definition': 'last MAP before index as baseline; nearest MAP at 17 scheduled points (5,10,15,20,25,30,40,50,60,75,90,105,120,135,150,165,180 min); any value <=85% baseline is an event', 'real': rows('SELECT COUNT(*) AS n, SUM(event) AS events, AVG(event) AS rate, AVG(scheduled_points) AS mean_scheduled_points FROM cantais_real WHERE scheduled_points>=10'), 'fake': rows('SELECT COUNT(*) AS n, SUM(event) AS events, AVG(event) AS rate, AVG(scheduled_points) AS mean_scheduled_points FROM cantais_fake WHERE scheduled_points>=10')}
    pooled = rows(f"\n        WITH real AS (\n          SELECT\n            AVG(post_min - pre_mean) AS min_change,\n            AVG(mean_30_60 - pre_mean) AS mean_30_60_change,\n            AVG(mean_60_90 - pre_mean) AS mean_60_90_change,\n            AVG(mean_90_120 - pre_mean) AS mean_90_120_change,\n            COUNT(*) AS n\n          FROM (\n            SELECT r.*, AVG(m.vm5) FILTER (WHERE m.datetime >= r.givenat AND m.datetime < r.givenat + INTERVAL 60 MINUTE) AS mean_30_60,\n                         AVG(m.vm5) FILTER (WHERE m.datetime >= r.givenat + INTERVAL 60 MINUTE AND m.datetime < r.givenat + INTERVAL 90 MINUTE) AS mean_60_90,\n                         AVG(m.vm5) FILTER (WHERE m.datetime >= r.givenat + INTERVAL 90 MINUTE AND m.datetime <= r.givenat + INTERVAL 120 MINUTE) AS mean_90_120\n            FROM real_combined r JOIN read_parquet('{MAP_GLOB}') m ON m.patientid=r.patientid AND m.datetime BETWEEN r.givenat AND r.givenat+INTERVAL 120 MINUTE AND m.vm5 IS NOT NULL\n            GROUP BY ALL\n          )\n        ), fake AS (\n          SELECT AVG(post_min - pre_mean) AS min_change,\n                 AVG(mean_30_60 - pre_mean) AS mean_30_60_change,\n                 AVG(mean_60_90 - pre_mean) AS mean_60_90_change,\n                 AVG(mean_90_120 - pre_mean) AS mean_90_120_change,\n                 COUNT(*) AS n\n          FROM fake_best\n        )\n        SELECT 'real_combined' AS group_name, * FROM real\n        UNION ALL\n        SELECT 'fake_matched' AS group_name, * FROM fake\n        ")
    result['task1_pooled_real_vs_fake'] = {'matching': 'same patient; offsets +/-8, +/-12, +/-16h; no target drug +/-4h; nearest pre-MAP/slope/temperature distance with exact reconstructed pressor-state penalty', 'outcomes': 'minimum 0-120m and mean changes at 30-60, 60-90, 90-120m relative to pre -30-0m MAP', 'pooled_groups': pooled}
else:
    result['map_audit'] = {'status': 'not_run', 'reason': 'paired-patient kill line failed'}
(OUT / 'hirid_metamizole_audit.json').write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding='utf-8')
print(json.dumps(result, ensure_ascii=True, indent=2))
