from __future__ import annotations
import json
from pathlib import Path
from config import DUCKDB_TEMP, HIRID_MAP_GLOB, HIRID_ROOT, RESULTS_DIR, SICDB_ROOT
import duckdb
ROOT = HIRID_ROOT
OUT = RESULTS_DIR
OUT.mkdir(parents=True, exist_ok=True)
PHARMA_GLOB = str(ROOT / 'raw_stage' / 'pharma_records' / 'csv' / 'part-*.csv').replace('\\', '/')
CSV_COLUMNS = "{patientid: 'INTEGER', pharmaid: 'INTEGER', givenat: 'TIMESTAMP', enteredentryat: 'TIMESTAMP', givendose: 'DOUBLE', cumulativedose: 'DOUBLE', fluidamount_calc: 'DOUBLE', cumulfluidamount_calc: 'DOUBLE', doseunit: 'VARCHAR', route: 'VARCHAR', infusionid: 'VARCHAR', typeid: 'INTEGER', subtypeid: 'DOUBLE', recordstatus: 'INTEGER'}"
MET = (1000605,)
PARA = (1000489, 1000490)
TARGET = MET + PARA
PRESSORS = (1000462, 1000656, 1000657, 1000658, 71, 1000750, 1000649, 1000650, 1000655, 112, 113)
SEDATIVE_BOLUS = (1000700, 1001054, 251, 1001052, 1000691, 1000239, 245, 390, 442, 1000400, 1000857)
BP_LOWERING = (1000763, 1001047, 1000252, 1000695, 1000867, 1000243, 1000868, 1001048, 1001141, 1001142, 117, 1000596, 1000436, 94, 242, 1000477)
con = duckdb.connect()
con.execute("SET memory_limit='768MB'")
con.execute('SET threads=2')
con.execute('SET preserve_insertion_order=false')
con.execute(f"SET temp_directory='{DUCKDB_TEMP.as_posix()}'")
con.execute(f"\n    CREATE TEMP TABLE target AS\n    SELECT ROW_NUMBER() OVER () AS target_id,\n           patientid::INTEGER AS patientid,\n           pharmaid::INTEGER AS pharmaid,\n           CASE WHEN pharmaid=1000605 THEN 'metamizole' ELSE 'paracetamol' END AS drug,\n           givenat::TIMESTAMP AS givenat,\n           route, givendose::DOUBLE AS givendose,\n           infusionid::VARCHAR AS infusionid\n    FROM read_csv('{PHARMA_GLOB}', union_by_name=true, header=true, columns={CSV_COLUMNS}, ignore_errors=true)\n    WHERE pharmaid IN {TARGET}\n      AND givenat IS NOT NULL\n      AND route IN ('iv-inj', 'iv-inf', 'cv-inj', 'cv-inf')\n      AND givendose > 0\n      AND (recordstatus & 2) = 0 AND (recordstatus & 32) = 0\n    ")
con.execute(f"\n    CREATE TEMP TABLE pressor_raw AS\n    SELECT patientid::INTEGER AS patientid, pharmaid::INTEGER AS pharmaid,\n           givenat::TIMESTAMP AS givenat, givendose::DOUBLE AS givendose,\n           infusionid::VARCHAR AS infusionid\n    FROM read_csv('{PHARMA_GLOB}', union_by_name=true, header=true, columns={CSV_COLUMNS}, ignore_errors=true)\n    WHERE pharmaid IN {PRESSORS}\n      AND patientid IN (SELECT DISTINCT patientid FROM target)\n      AND givenat IS NOT NULL AND givendose > 0\n      AND route IN ('cv-inf', 'iv-inf')\n      AND (recordstatus & 2) = 0 AND (recordstatus & 32) = 0\n    ")
con.execute('\n    CREATE TEMP TABLE pressor_intervals AS\n    WITH x AS (\n      SELECT *, LEAD(givenat) OVER (PARTITION BY patientid, infusionid ORDER BY givenat) AS next_at,\n                   LAG(givendose) OVER (PARTITION BY patientid, infusionid ORDER BY givenat) AS prev_dose\n      FROM pressor_raw\n    )\n    SELECT patientid, infusionid, givenat AS start_at,\n           CASE WHEN next_at IS NOT NULL AND next_at <= givenat + INTERVAL 15 MINUTE\n                THEN next_at ELSE givenat + INTERVAL 10 MINUTE END AS stop_at,\n           CASE WHEN prev_dose IS NOT NULL AND givendose <> prev_dose THEN 1 ELSE 0 END AS dose_change\n    FROM x\n    ')
con.execute('\n    CREATE TEMP TABLE target_timeline AS\n    SELECT t.*,\n           LAG(t.drug) OVER (PARTITION BY t.patientid ORDER BY t.givenat, t.target_id) AS prev_drug,\n           LAG(t.givenat) OVER (PARTITION BY t.patientid ORDER BY t.givenat, t.target_id) AS prev_at,\n           LEAD(t.givenat) OVER (PARTITION BY t.patientid ORDER BY t.givenat, t.target_id) AS next_at,\n           CASE WHEN EXISTS (\n             SELECT 1 FROM pressor_intervals p\n             WHERE p.patientid=t.patientid AND p.start_at <= t.givenat AND t.givenat < p.stop_at\n           ) THEN TRUE ELSE FALSE END AS pressor_active,\n           CASE WHEN EXISTS (\n             SELECT 1 FROM pressor_intervals p\n             WHERE p.patientid=t.patientid\n               AND p.start_at >= t.givenat - INTERVAL 30 MINUTE\n               AND p.start_at < t.givenat\n               AND p.dose_change=1\n           ) THEN 1 ELSE 0 END AS pressor_pre30_change\n    FROM target t\n    ')
con.execute('\n    CREATE TEMP TABLE residual AS\n    SELECT t.target_id,\n           MAX(CASE WHEN o.givenat < t.givenat THEN 1 ELSE 0 END) AS other_drug_prev4h,\n           MAX(CASE WHEN o.givenat > t.givenat THEN 1 ELSE 0 END) AS other_drug_next2h\n    FROM target t LEFT JOIN target o\n      ON o.patientid=t.patientid AND o.drug <> t.drug\n     AND ((o.givenat >= t.givenat - INTERVAL 4 HOUR AND o.givenat < t.givenat)\n       OR (o.givenat > t.givenat AND o.givenat <= t.givenat + INTERVAL 2 HOUR))\n    GROUP BY t.target_id\n    ')
con.execute(f"\n    CREATE TEMP TABLE cointervention AS\n    SELECT t.target_id,\n           MAX(CASE WHEN p.pharmaid::INTEGER IN {SEDATIVE_BOLUS} THEN 1 ELSE 0 END) AS sedative_bolus_2h,\n           MAX(CASE WHEN p.pharmaid::INTEGER IN {BP_LOWERING} THEN 1 ELSE 0 END) AS bp_lowering_2h\n    FROM target t LEFT JOIN read_csv('{PHARMA_GLOB}', union_by_name=true, header=true, columns={CSV_COLUMNS}, ignore_errors=true) p\n      ON p.patientid::INTEGER=t.patientid\n     AND p.pharmaid::INTEGER NOT IN {TARGET}\n     AND p.givenat::TIMESTAMP BETWEEN t.givenat - INTERVAL 2 HOUR AND t.givenat + INTERVAL 2 HOUR\n     AND p.givendose::DOUBLE > 0\n     AND (p.recordstatus::INTEGER & 2) = 0 AND (p.recordstatus::INTEGER & 32) = 0\n     AND p.route IN ('iv-inj', 'iv-inf', 'cv-inj', 'cv-inf')\n    GROUP BY t.target_id\n    ")
con.execute('\n    CREATE TEMP TABLE annotated AS\n    SELECT t.*,\n           COALESCE(r.other_drug_prev4h,0) AS other_drug_prev4h,\n           COALESCE(r.other_drug_next2h,0) AS other_drug_next2h,\n           COALESCE(c.sedative_bolus_2h,0) AS sedative_bolus_2h,\n           COALESCE(c.bp_lowering_2h,0) AS bp_lowering_2h\n    FROM target_timeline t\n    LEFT JOIN residual r ON r.target_id=t.target_id\n    LEFT JOIN cointervention c ON c.target_id=t.target_id\n    ')

def rows(sql: str):
    cur = con.execute(sql)
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, row)) for row in cur.fetchall()]

def summarize(washout_minutes: int) -> dict:
    name = f'marked_{washout_minutes}'
    seq_name = f'seq_{washout_minutes}'
    con.execute(f'DROP TABLE IF EXISTS {name}')
    con.execute(f'DROP TABLE IF EXISTS {seq_name}')
    con.execute(f'\n        CREATE TEMP TABLE {name} AS\n        SELECT *,\n               CASE WHEN prev_at IS NOT NULL\n                          AND EPOCH(givenat-prev_at)/60.0 >= {washout_minutes}\n                          AND next_at IS NOT NULL\n                          AND EPOCH(next_at-givenat)/60.0 >= {washout_minutes}\n                          AND pressor_pre30_change=0\n                    THEN 1 ELSE 0 END AS current_keep\n        FROM target_timeline\n        ')
    con.execute(f'\n        CREATE TEMP TABLE {seq_name} AS\n        SELECT *, LAG(current_keep) OVER (PARTITION BY patientid ORDER BY givenat, target_id) AS prev_current_keep\n        FROM {name}\n        ')
    eligible = rows(f'\n        SELECT pressor_active, drug,\n               COUNT(*) AS administrations,\n               COUNT(DISTINCT patientid) AS patients\n        FROM {name}\n        WHERE current_keep=1\n        GROUP BY ALL ORDER BY pressor_active, drug\n        ')
    transitions = rows(f'\n        SELECT pressor_active, prev_drug, drug,\n               COUNT(*) AS transitions,\n               COUNT(DISTINCT patientid) AS patients\n        FROM {seq_name}\n        WHERE current_keep=1 AND prev_current_keep=1 AND prev_drug IS NOT NULL AND drug<>prev_drug\n        GROUP BY ALL ORDER BY pressor_active, prev_drug, drug\n        ')
    patient_counts = rows(f"\n        WITH t AS (\n          SELECT * FROM {seq_name}\n          WHERE current_keep=1 AND prev_current_keep=1 AND prev_drug IS NOT NULL AND drug<>prev_drug\n        ), p AS (\n          SELECT patientid, pressor_active,\n                 COUNT(*) AS transitions,\n                 COUNT(*) FILTER (WHERE prev_drug='metamizole' AND drug='paracetamol') AS met_to_para,\n                 COUNT(*) FILTER (WHERE prev_drug='paracetamol' AND drug='metamizole') AS para_to_met\n          FROM t GROUP BY patientid, pressor_active\n        )\n        SELECT pressor_active,\n               COUNT(*) FILTER (WHERE transitions>=1) AS patients_with_any_strict_transition,\n               COUNT(*) FILTER (WHERE met_to_para>=1 AND para_to_met>=1) AS patients_with_bidirectional_sequence,\n               SUM(transitions) AS strict_transition_events\n        FROM p GROUP BY pressor_active ORDER BY pressor_active\n        ")
    return {'washout_minutes': washout_minutes, 'eligible_administrations': eligible, 'strict_transition_counts': transitions, 'patient_counts': patient_counts}
summaries = {str(w): summarize(w) for w in (120, 90)}
primary120 = summaries['120']['patient_counts']
active120 = next((r for r in primary120 if r['pressor_active']), None)
active120_n = int((active120 or {}).get('patients_with_bidirectional_sequence') or 0)
fallback_triggered = active120_n < 200
selected = 90 if fallback_triggered else 120
result = {'dataset': 'HiRID 1.1.1', 'outcome_blind': True, 'definition': {'sequence': 'adjacent target administrations must switch drug category; prior drug retained as covariate', 'washout': 'distance to previous and next any-target administration must be >= threshold', 'pressor_exclusion': 'any reconstructed pressor dose change in [givenat-30m, givenat) excludes the administration', 'sedation': 'not excluded at this sample-size stage; planned covariate under the requested specification', 'pressor_stratification': "current administration's reconstructed pressor infusion state"}, 'primary_threshold': {'threshold': 200, 'metric': 'patients_with_bidirectional_sequence in pressor_active stratum', 'washout_120_active_bidirectional_patients': active120_n, 'fallback_triggered': fallback_triggered, 'selected_washout_minutes': selected, 'fallback_rule': 'use >=90 minutes once if the >=120-minute count is below 200; no further relaxation'}, 'summaries': summaries}
con.execute('\n    CREATE TEMP TABLE annotated_seq AS\n    SELECT a.*,\n           LAG(a.target_id) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_id,\n           LAG(a.givenat) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_at,\n           LAG(a.drug) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_drug,\n           LAG(a.pressor_pre30_change) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_pre30_change,\n           LAG(a.other_drug_prev4h) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_other_drug_prev4h,\n           LAG(a.other_drug_next2h) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_other_drug_next2h,\n           LAG(a.sedative_bolus_2h) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_sedative_bolus_2h,\n           LAG(a.bp_lowering_2h) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS previous_bp_lowering_2h,\n           LEAD(a.target_id) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS next_id,\n           LEAD(a.givenat) OVER (PARTITION BY a.patientid ORDER BY a.givenat, a.target_id) AS next_at\n    FROM annotated a\n    ')
con.execute('\n    CREATE TEMP TABLE pressor_edges AS\n    SELECT *,\n           EPOCH(givenat-previous_at)/60.0 AS previous_gap_minutes,\n           EPOCH(next_at-givenat)/60.0 AS next_gap_minutes\n    FROM annotated_seq\n    WHERE pressor_active=TRUE AND previous_drug IS NOT NULL AND drug<>previous_drug\n    ')

def diagnostic_counts(condition: str) -> dict:
    edge_rows = rows(f"\n        WITH e AS (SELECT * FROM pressor_edges WHERE {condition}),\n        p AS (\n          SELECT patientid,\n                 COUNT(*) AS edges,\n                 COUNT(*) FILTER (WHERE previous_drug='metamizole' AND drug='paracetamol') AS met_to_para,\n                 COUNT(*) FILTER (WHERE previous_drug='paracetamol' AND drug='metamizole') AS para_to_met\n          FROM e GROUP BY patientid\n        ), endpoints AS (\n          SELECT current_id FROM (SELECT target_id AS current_id FROM e)\n          UNION\n          SELECT previous_id FROM e\n        )\n        SELECT (SELECT COUNT(*) FROM p) AS patients,\n               (SELECT COUNT(*) FROM p WHERE met_to_para>0 AND para_to_met>0) AS bidirectional_patients,\n               (SELECT COUNT(*) FROM e) AS transition_edges,\n               (SELECT COUNT(*) FROM endpoints) AS participating_administrations\n        ")
    return edge_rows[0]
step3 = 'previous_gap_minutes >= 120 AND next_gap_minutes >= 120 AND pressor_pre30_change=0 AND previous_pre30_change=0'
step4 = step3 + ' AND other_drug_prev4h=0 AND other_drug_next2h=0 AND sedative_bolus_2h=0 AND bp_lowering_2h=0 AND previous_other_drug_prev4h=0 AND previous_other_drug_next2h=0 AND previous_sedative_bolus_2h=0 AND previous_bp_lowering_2h=0'
result['pressor_stepwise_diagnostic'] = {'starting_unrestricted_pressor_transition_patients': diagnostic_counts('TRUE')['patients'], 'steps': [{'step': 0, 'rule': 'unrestricted adjacent strict alternation during pressor-active current administration', **diagnostic_counts('TRUE')}, {'step': 1, 'rule': 'previous target administration gap >=120 minutes', **diagnostic_counts('previous_gap_minutes >= 120')}, {'step': 2, 'rule': 'previous and next target administration gaps >=120 minutes', **diagnostic_counts('previous_gap_minutes >= 120 AND next_gap_minutes >= 120')}, {'step': 3, 'rule': 'step 2 plus no pressor dose change in the 30 minutes before current administration', **diagnostic_counts(step3)}, {'step': 4, 'rule': 'step 3 plus original residual and named co-intervention exclusions at current administration', **diagnostic_counts(step4)}], 'adjacent_interval_distribution_minutes': rows('\n        SELECT COUNT(*) AS n,\n               MEDIAN(previous_gap_minutes) AS median_minutes,\n               QUANTILE_CONT(previous_gap_minutes, 0.25) AS q1_minutes,\n               QUANTILE_CONT(previous_gap_minutes, 0.75) AS q3_minutes\n        FROM pressor_edges\n        ')[0]}
step2 = result['pressor_stepwise_diagnostic']['steps'][2]
result['new_rule_pressor_sample'] = {'rule': 'adjacent strict alternation during pressor-active current administration; previous and next target gaps >=120 minutes; no pre-30-minute NE stability exclusion', 'outcome_blind': True, 'patients': int(step2['patients']), 'bidirectional_patients': int(step2['bidirectional_patients']), 'participating_administrations': int(step2['participating_administrations']), 'transition_edges': int(step2['transition_edges'])}
(OUT / 'hirid_metamizole_crossover_washout_sample_audit.json').write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding='utf-8')
print(json.dumps(result, indent=2, ensure_ascii=True))
